Add version check in release workflow

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -41,6 +41,7 @@ jobs:
         run: |
           # 从Cargo.toml中提取版本号
           version=$(grep -E ^version Cargo.toml|awk -F "[\"]" '{print $2}')
+          if [ -z "$version" ]; then echo "version not found"; exit 1; fi
           if $(gh release delete v${version} -y --cleanup-tag); 
             then echo "delete old release"; 
             else echo "no old release";
